### ISSUE TITLE
Missing columns in model YAML files

### ISSUE THREAD

**Issue by jastingo** [fullstorydev/dbt_fullstory#27]
Our team recently installed v0.7.0 of `dbt_fullstory` and it caused our tests to fail as there are columns defined in model SQL files but not in the YAML files. Below are the columns missing:

`identified_users.yml`:

- name: `last_updated_time`
- name: `last_processed_time`

`sessions.yml`:

- name: `desc_row_num`

`events.yml`:

- name: `element_definition_id`
- name: `user_display_name`
- name: `target_raw_selector`
- name: `target_text`
- name: `user_properties`
- name: `user_id`
- name: `target_masked`

**Comment by huttotw** [comment]
Hey @jastingo thanks for reporting this! I just created PR  #28 to add these docs and as soon as it is merged I'll bump the version!

**Comment by huttotw** [comment]
@jastingo release [v0.7.1](https://github.com/fullstorydev/dbt_fullstory/releases/tag/v0.7.1) is now available.

**Comment by jastingo** [comment]
@huttotw looks like there are still two missing column names in `events.yml`:

- `user_email`
- `additional_element_definition_ids`
